[package]
name = "flylang"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
either = "1.15.0"
enum_variant_type = "0.3.1"
regex = "1.12.2"
toml = "0.9.8"
