# Flylang settings
[language]
compiler="flypreter"
compilers_folders=[
  "$FLYLANG/addons"
]

[language.dependencies]
global_folders=[
  "$FLYLANG/.globdeps"
]
local_folder="$CWD/.deps"

# List of dependencies for the package
[package.dependencies]
"flylang/core" = "1.0.0"
